import { motion } from "motion/react";
import { C, FONT_BODY } from "../theme";
import Slide from "../components/Slide";
import Stagger from "../components/Stagger";
import RiskCard from "../components/RiskCard";

export default function SlideRiskMap2() {
  const risks = [
    { icon: "\uD83E\uDDFE", risk: "Irrecoverable VAT", exposure: "20% VAT on full charge. Dead cost ~£4.40/hr.", elimination: "Model B: No VAT on worker earnings. VAT on platform fee only. Saves ~£600K/yr at scale." },
    { icon: "\uD83D\uDCB0", risk: "Cost Opacity", exposure: "Blended rates with no breakdown.", elimination: "Worker rate, platform fee, and VAT shown as separate line items on every invoice. Full audit trail of every payment, routed correctly based on CEST determination." },
    { icon: "\uD83D\uDE1E", risk: "Worker Take-Home Squeeze", exposure: "£14-16/hr after umbrella deductions.", elimination: "SE workers receive full agreed rate. PAYE workers get proper payslip. No umbrella deductions." },
    { icon: "\uD83D\uDCCB", risk: "CQC Vulnerability", exposure: "Evidence scattered across agencies.", elimination: "CQC Inspection-Ready reports generated by CRM. Full credentials, CEST, insurance in one download." },
    { icon: "\uD83D\uDCDD", risk: "No SE Evidence", exposure: "Substitutions and declines not tracked.", elimination: "Every decline logged. Substitution workflow with full audit trail. Evidence built continuously." },
    { icon: "\uD83D\uDD17", risk: "Single Agency Dependency", exposure: "Lose access to workers and all evidence if relationship fails.", elimination: "Workers onboarded with own credentials. You retain all compliance data regardless." },
  ];

  return (
    <Slide bg={C.dark}>
      <div style={{ maxWidth: 920, padding: "0 40px", width: "100%" }}>
        <Stagger>
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
            <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase", color: C.sage, fontFamily: FONT_BODY }}>
              Risk Elimination (continued)
            </div>
            <div style={{ flex: 1, height: 1, background: `${C.sage}30` }} />
          </div>
        </Stagger>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12, marginBottom: 24 }}>
          {risks.map((r, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.08, duration: 0.6 }}
            >
              <RiskCard {...r} />
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9, duration: 0.6 }}
          style={{
            background: `${C.sage}10`,
            border: `1.5px solid ${C.sage}40`,
            borderRadius: 16,
            padding: "20px 28px",
            textAlign: "center",
          }}
        >
          <span style={{ fontSize: 15, fontWeight: 700, color: C.sage, fontFamily: FONT_BODY }}>
            Residual risk to provider: Zero.
          </span>
          <span style={{ fontSize: 13, color: `${C.cream}88`, marginLeft: 10, fontFamily: FONT_BODY }}>
            A structural consequence of removing the umbrella and using HMRC's own tools.
          </span>
        </motion.div>
      </div>
    </Slide>
  );
}
